# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lyne' do

  use_frameworks!

  # Pods for Lyne

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'SCLAlertView'
  pod 'OneSignal', '>= 2.5.2', '< 3.0'

end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.5.2', '< 3.0'
end
