# Uncomment the next line to define a global platform for your project
platform :ios, ’10.3’

target 'Lyne' do

 use_frameworks!
  # Pods for Lyne

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'SCLAlertView'
  pod 'OneSignal', '>= 2.5.2', '< 3.0'
  pod ‘Alamofire’

end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.5.2', '< 3.0'
end
